version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tamilnadu_backend_app:latest
    container_name: tamilnadu_backend_app
    env_file:
      - ./.env
    depends_on:
      - broker
    volumes:
      - static_data:/usr/src/app/static_root
      - ./backend/uploads:/usr/src/app/backend/uploads
    networks:
      - backend_network
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: tamilnadu_backend_worker:latest
    container_name: tamilnadu_backend_worker
    env_file:
      - ./.env
    command: >
      celery -A inzighted --workdir /usr/src/app/backend worker -l info --concurrency=2
    depends_on:
      - broker
      - app
    volumes:
      - static_data:/usr/src/app/static_root
      - ./backend/uploads:/usr/src/app/backend/uploads
    networks:
      - backend_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: tamilnadu_nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - static_data:/usr/src/app/static_root:ro
      - ./backend/uploads:/usr/src/app/backend/uploads:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend_network
    restart: unless-stopped

  broker:
    image: "redis:7-alpine"
    container_name: tamilnadu_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - backend_network
    ports:
      - "6379:6379"

volumes:
  static_data:
  redis_data:

networks:
  backend_network:
    driver: bridge
